version: '3.8'

services:
  online-shop:
    container_name: online-shop-container
    image: online-shop-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    networks:
      - dev-network

networks:
  dev-network:
    external: true
